name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 添加权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 设置 JDK 17 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    # 构建项目
    - name: Build with Gradle
      run: ./gradlew clean build

    # 如果你使用了 Gradle Shadow 插件构建 JAR
    - name: Build Plugin with ShadowJar
      run: ./gradlew shadowJar

    # 将构建的插件保存为构建产物
    - name: Archive Plugin Artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: build/libs/*.jar  # 根据实际输出路径调整

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 发布到 GitHub Releases
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
